# Generated by Django 4.2.23 on 2025-11-21 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(verbose_name='總限量數')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='已預留數量')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='已售出數量')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='結束時間')),
                ('status', models.CharField(choices=[('pending', '待開始'), ('active', '進行中'), ('ended', '已結束')], default='pending', max_length=20, verbose_name='活動狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '搶購活動',
                'verbose_name_plural': '搶購活動',
                'db_table': 'flash_sale_events',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='商品編號')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='訂單編號')),
                ('user_email', models.EmailField(max_length=254, verbose_name='用戶Email')),
                ('payment_method', models.CharField(choices=[('credit_card', '信用卡'), ('line_pay', 'Line Pay')], max_length=20, null=True, verbose_name='付款方式')),
                ('payment_deadline', models.DateTimeField(null=True, verbose_name='付款期限')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款時間')),
                ('shipping_priority', models.IntegerField(blank=True, null=True, verbose_name='出貨順位')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('shipped', '已出貨'), ('completed', '已完成'), ('cancelled', '已取消'), ('expired', '已逾期')], default='pending', max_length=20, verbose_name='訂單狀態')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('flash_sale_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.flashsaleevent', verbose_name='搶購活動')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'db_table': 'sales_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小計')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='商品')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.salesorder', verbose_name='訂單')),
            ],
            options={
                'verbose_name': '訂單明細',
                'verbose_name_plural': '訂單明細',
                'db_table': 'sales_order_items',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0, verbose_name='實際庫存')),
                ('quantity_reserved', models.IntegerField(default=0, verbose_name='預留庫存')),
                ('quantity_available', models.IntegerField(default=0, verbose_name='可售庫存')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('version', models.IntegerField(default=0, verbose_name='版本號')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shop.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '庫存',
                'verbose_name_plural': '庫存',
                'db_table': 'inventory',
            },
        ),
        migrations.AddField(
            model_name='flashsaleevent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='shop.product', verbose_name='商品'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='sales_order_order_n_51d36c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['user_email'], name='sales_order_user_em_34be69_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['paid_at'], name='sales_order_paid_at_a92444_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['flash_sale_event', 'status', 'paid_at'], name='sales_order_flash_s_dcea73_idx'),
        ),
    ]
